### ISSUE TITLE
Force HTTPS on API key generation

### ISSUE THREAD

**Issue by makaimc** [GSA/Developer-Feedback-for-Government-APIs#37]
The page that generates and distributes API keys to users does not provide HTTPS. http://niaid.github.io/3dpx_api/api_key/

**Comment by makaimc** [comment]
Actually the entire website and API should force HTTPS otherwise keys can be leaked. This should have an NIH label but I didn't see one available.

**Comment by gbinal** [comment]
Moved  to https://github.com/niaid/3dpx_api/issues/17
